# This is the documentation for GetTubeInfo.py 
1. This might be better to open in an actual Jupyter Notebook with [Anaconda](https://www.anaconda.com/) instead of VSCode
1. I hope that putting the code into cells will help the next __students__ see my intention behind writing things the way I do, and I hope that it will make the function of the code clearer. 
1. When I say __students__, I still assume very little or no experience, if you are experienced, good for you, this still is useful. 

-Evan Carpenter

1.    __format_database__() ––> df

1.    __locate_tube_row__(input_tube_ID) ––> tuberow 

1.    __filter_columns__(tuberow) ––> row_information

1.    __format_columns__(row_information) ––> dictionary of formattted values, good tube? (boolean)

1.    __get_final_tuple__(input_tube_ID) ––> string to print, good tube? (boolean)

-    [pathlib.Path](https://docs.python.org/3/library/pathlib.html) An OS independent way to find files on computers, I prefer this over os.path, which can behave differently between Operating Systems.

-    [pandas](https://pandas.pydata.org/) one of the best data science libraries in python. Almost everything in the beginning of this code is a pandas dataframe. 

-   [datetime.datetime, datetime.timedelta](https://www.w3schools.com/python/python_datetime.asp) I mostly use this to format dates and find the difference in dates between the first and second tension test. 

-   [os.path.getctime](https://www.geeksforgeeks.org/python-os-path-getctime-method/) Used for finding the last time a file was modified

-   [re.match](https://docs.python.org/3/library/re.html) I only use this once to check that the date string is an acceptable format. It was more out of curiosity than necessity, and can easily be replaced.

In [1]:
from pathlib import Path 
import pandas as pd
from datetime import datetime, timedelta
from os.path import getctime
from re import match

#### To get to TUBEDB.txt
I use Path to

In [2]:
home = Path.home()
GDrive_to_DB = Path("Google Drive/Shared drives/sMDT Tube Testing Reports/TUBEDB.txt")
path_to_local = Path.joinpath(Path("").absolute().parent, "Verifying", "TUBEDB.txt")
final_path = Path.joinpath(home, GDrive_to_DB)

print("home:         ", home)
print("GDrive_to_DB: ", GDrive_to_DB)
print("path_to_local:", path_to_local)
print("final_path:   ", final_path)
print(final_path.exists())

home:          /Users/evan
GDrive_to_DB:  Google Drive/Shared drives/sMDT Tube Testing Reports/TUBEDB.txt
path_to_local: /Users/evan/Verifying/TUBEDB.txt
final_path:    /Users/evan/Google Drive/Shared drives/sMDT Tube Testing Reports/TUBEDB.txt
True

# format_database()
-    Opens the path to Google Drive to get to the TUBEDB.txt file in the shared drive. 
-    No inputs, outputs a pandas DataFrame

In [3]:
try:
    df = pd.read_csv(final_path, 
                    names = ["ID", "T1", "T2", "DC", "FV"],  
                    delimiter = "|",
                    memory_map = True, 
                    skiprows=2)
    path_used = final_path
except FileNotFoundError:
    
    
    print(f'''

    1.) Hmm... Could not access {home}/Google Drive/Shared drives/sMDT Tube Testing Reports/TUBEDB.txt
    2.) Trying local path {path_to_local}

    ''')
    
    
    try: 
        
        df = pd.read_csv(path_to_local, 
                    names = ["ID", "T1", "T2", "DC", "FV"],  
                    delimiter = "|",
                    memory_map = True)
        path_used = path_to_local
    except FileNotFoundError:
        exit("If you get this message, either install Google Drive Desktop or copy TUBEDB.txt from the Google Drive into {path_to_local.parent}\n")

        
        

display(df)

,ID,T1,T2,DC,FV
0,MSU00212 OLD 2020-01-20 5.00E-06 -1.00 PASS,-------- ------- ---- ------- ---- -,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO Accident
1,MSU00213 OLD 2020-01-20 1.33E-08 -1.00 FAIL,20-02-21 1624.52 94.0 355.370 pass B,0.00 0.000 51D Pass2*,20-08-27 CAEN 0.58 255841 OK,20/08/27 4 NO BadEP
2,MSU00215 OLD 2020-01-20 1.49E-07 -1.00 FAIL,20-02-21 1624.66 94.4 358.401 pass B,-0.20 1.138 51D Pass2*,20-07-31 CAEN 2.82 468061 WARN,20/07/31 5 NO BadEP
3,MSU00218 OLD 2020-01-20 8.15E-07 -1.00 PASS,20-03-05 1624.23 59.0 140.000 fail A,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO Accident
4,MSU00219 OLD 2020-07-02 2.90E-07 -1.00 FAIL,20-08-14 1625.11 95.0 362.971 pass C,-0.50 3.810 226D Pass2*,20-08-27 CAEN 1.68 124220 OK,20/08/27 4 NO BadEP
...,...,...,...,...,...
16364,MSU18355 IHEP 2022-08-16 3.06E-08 0.00 PASS,22-08-02 1624.61 93.5 351.600 pass B,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO
16365,MSU18366 IHEP 2022-08-16 2.16E-08 0.00 PASS,22-07-29 1624.63 93.5 351.600 pass B,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO
16366,MSU18422 IHEP 2022-08-16 2.75E-08 0.00 PASS,22-07-29 1624.52 94.5 359.161 pass B,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO
16367,MSU18460 IHEP 2022-08-16 3.29E-08 0.00 PASS,22-08-10 1624.89 94.5 359.161 pass C,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO
16368,MSU18492 IHEP 2022-08-16 2.44E-08 0.00 PASS,22-08-02 1624.78 93.5 351.600 pass C,------ -------- ---- -----,-------- ---- ------ ------- ----,--/--/-- 0 NO

This next part should only be run if the file is being run in another file.
 
In GetTubeInfo, \_\_name\_\_ == "\_\_main\_\_", but if GetTubeInfo is used in another file, like in Verify.py when I say "__import GetTubeInfo__", then \_\_name\_\_ == "GetTubeInfo"

In [4]:
if __name__ == "GetTubeInfo":
    print(f"Database File is from: {path_used}")
    print("Last Updated:", datetime.fromtimestamp(os.path.getctime(path_used)))

# Just for demonstration, lets print it out anyways:

print(f"Database File is from: {final_path}")
print(f"Last Updated: {datetime.fromtimestamp(getctime(final_path))}")

Database File is from: /Users/evan/Google Drive/Shared drives/sMDT Tube Testing Reports/TUBEDB.txt
Last Updated: 2022-08-20 20:12:19.350945

????????????????????????????????????????????????????????????????????????
### Formatting the Dataframe with lambda 

Here I format the dataframe so it is more easily usable, I want each column to be a distinct parameter of the tube. 

I use unnamed lambda expressions to apply a function to every item in the dataframe, then split the dataframe by it's lists into multiple DataFrames, which I stitch together using pd.concat

In order to understand what the lambda function does to every item in the dataframe, I make two __named__ lambda expressions in the next cell

In [5]:
first_lambda = lambda string: " ".join(string.split()) # This changes all separating space to just single space
second_lambda = lambda string: string.split(" ") # This splits strign into list with single space as delimiter

example_cell_in_dataframe = "This   makes a     list  that  properly  delimits by       space"

print(example_cell_in_dataframe)

first_modification = first_lambda(example_cell_in_dataframe)
print(first_modification)

second_modification = second_lambda(first_modification)
print(second_modification)

This   makes a     list  that  properly  delimits by       space
This makes a list that properly delimits by space
['This', 'makes', 'a', 'list', 'that', 'properly', 'delimits', 'by', 'space']

¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿

In [7]:
print("Unmodified:")
display(df)

df = df.applymap(lambda string: " ".join(string.split()))

print("After first modification, all spaces are now 1 space:")
display(df)

df = df.applymap(lambda string: string.split(" "))

print("After second modification, all cells are a list delimited by 1 space:")
display(df)

# Now to split the dataframe into multiple dataframes by their lists!
ID = pd.DataFrame(df["ID"].tolist()[2:], columns=["tubeID",  "End",     "Received", "leakrate", "bend", "flagE"])
display(ID) # Only using one example for simplicity, but feel free to display more!
T1 = pd.DataFrame(df["T1"].tolist()[2:], columns=["T1Date", "Length", "Frequency",  "Tension",  "flag", "L"])
T2 = pd.DataFrame(df["T2"].tolist()[2:], columns=["dFrequency",  "dTension",   "dDays",    "flag2"])
DC = pd.DataFrame(df["DC"].tolist()[2:], columns=["DCday",   "sys",     "DC",   "HVseconds",     "DCflag"])
FV = pd.DataFrame(df["FV"].tolist()[2:], columns=["ENDday",  "done?",   "ok",       "Comment",   "None", "None"])

newdf = pd.concat((ID, T1, T2, DC, FV), axis=1)

print("Final Dataframe!!")
display(newdf)

Unmodified:

,ID,T1,T2,DC,FV
0,"[MSU00212, OLD, 2020-01-20, 5.00E-06, -1.00, P...","[--------, -------, ----, -------, ----, -]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO, Accident]"
1,"[MSU00213, OLD, 2020-01-20, 1.33E-08, -1.00, F...","[20-02-21, 1624.52, 94.0, 355.370, pass, B]","[0.00, 0.000, 51D, Pass2*]","[20-08-27, CAEN, 0.58, 255841, OK]","[20/08/27, 4, NO, BadEP]"
2,"[MSU00215, OLD, 2020-01-20, 1.49E-07, -1.00, F...","[20-02-21, 1624.66, 94.4, 358.401, pass, B]","[-0.20, 1.138, 51D, Pass2*]","[20-07-31, CAEN, 2.82, 468061, WARN]","[20/07/31, 5, NO, BadEP]"
3,"[MSU00218, OLD, 2020-01-20, 8.15E-07, -1.00, P...","[20-03-05, 1624.23, 59.0, 140.000, fail, A]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO, Accident]"
4,"[MSU00219, OLD, 2020-07-02, 2.90E-07, -1.00, F...","[20-08-14, 1625.11, 95.0, 362.971, pass, C]","[-0.50, 3.810, 226D, Pass2*]","[20-08-27, CAEN, 1.68, 124220, OK]","[20/08/27, 4, NO, BadEP]"
...,...,...,...,...,...
16364,"[MSU18355, IHEP, 2022-08-16, 3.06E-08, 0.00, P...","[22-08-02, 1624.61, 93.5, 351.600, pass, B]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO]"
16365,"[MSU18366, IHEP, 2022-08-16, 2.16E-08, 0.00, P...","[22-07-29, 1624.63, 93.5, 351.600, pass, B]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO]"
16366,"[MSU18422, IHEP, 2022-08-16, 2.75E-08, 0.00, P...","[22-07-29, 1624.52, 94.5, 359.161, pass, B]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO]"
16367,"[MSU18460, IHEP, 2022-08-16, 3.29E-08, 0.00, P...","[22-08-10, 1624.89, 94.5, 359.161, pass, C]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO]"
16368,"[MSU18492, IHEP, 2022-08-16, 2.44E-08, 0.00, P...","[22-08-02, 1624.78, 93.5, 351.600, pass, C]","[------, --------, ----, -----]","[--------, ----, ------, -------, ----]","[--/--/--, 0, NO]"

AttributeError: 'list' object has no attribute 'split'

# locate_tube_row(input_tubeID)
-    Takes in a tube's ID (MSUXXXXX where X is 1-9, in regex this is MSU[0-9]{5}) and finds the ID in the tubeID column of the dataframe. 
-    There are three default letters that I use for quick testing which translate to IDs: d, f, b.
-    If something not of the form MSU[0-9]{5} (MSU followed by 5 numbers) is entered, the defaults are checked
-    If the ID is not found, the row returned is -1

In [14]:
DB = newdf
defaults = {"d": "MSU05123", # default (good)
            "f": "MSU01341", # fails multiple tests
            "b": "MSU00229"} # multiple tests missing--> "-----"
tubeID = input("input_tubeID: ") # in the .py this is just input_tubeID
try:
    istube = match("MSU[0-9]{5}", tubeID) 
    assert istube # this will raise an AssertionError if the ID does not look like "MSU" followed by 5 numbers
    # "tuberow, " unpacks just the first value of the tuple into the variable tuberow
    tuberow, = DB["tubeID"].index[ DB["tubeID"].str.contains(tubeID) ] # index of the row with True, which is row with ID
    print(tuberow)
except AssertionError: # This means ID was not valid, possibly a default key
    if len(tubeID) == 1 and tubeID in defaults.keys():
            tubeID = defaults[tubeID] # Default
            tuberow, = DB["tubeID"].index[ DB["tubeID"].str.contains(tubeID) ] # index of the row with True, which is row with ID
            print(tuberow)
    else: 
        print(-1)
except ValueError: # This means the ID is valid but not in the DB
    print(-2)

input_tubeID: MSU05123
4443

# filter_columns(tuberow)

In [15]:
fullrow = DB.iloc[tuberow]
row_information = {"tubeID"           :    fullrow.tubeID,

                   "Shipment_date"    :  fullrow.Received,

                   "Bend_flag"        :     fullrow.flagE,
                   "T1_date"          :    fullrow.T1Date,
                   "T1_length"        :    fullrow.Length,

                   "T1_tension"       :   fullrow.Tension,
                   "T1_flag"          :      fullrow.flag,


                   "T2_tension_delta" :  fullrow.dTension,
                   "T2_time_delta"    :     fullrow.dDays,
                   "T2_flag"          :     fullrow.flag2,

                   "DC_date"          :     fullrow.DCday,

                   "DC_DC"            :        fullrow.DC,
                   "DC_seconds"       : fullrow.HVseconds,
                   "DC_flag"          :    fullrow.DCflag,


                   "Final_flag"       :        fullrow.ok}
print(row_information)

{'tubeID': 'MSU05123', 'Shipment_date': '2021-06-23', 'Bend_flag': 'PASS', 'T1_date': '21-07-07', 'T1_length': '1624.72', 'T1_tension': '362.971', 'T1_flag': 'pass', 'T2_tension_delta': '-3.831', 'T2_time_delta': '13D', 'T2_flag': 'Pass2', 'DC_date': '21-06-23', 'DC_DC': '0.32', 'DC_seconds': '54820', 'DC_flag': 'OK', 'Final_flag': 'YES'}

# format_values(row_information)